---
# Tasks for cleaning up package-related items

- name: Clean package cache (keep only the most recent version)
  command: paccache -rk1
  changed_when: true
  become: true
  tags: [ maintenance, cleanup, packages, cache ]

- name: Remove all cached versions of uninstalled packages
  command: paccache -ruk0
  changed_when: true
  become: true
  tags: [ maintenance, cleanup, packages, cache ]

- name: Remove *-debug packages
  shell: pacman -Qq | grep -- '-debug$' | xargs pacman -Rns --noconfirm
  register: debug_packages
  changed_when: debug_packages.stdout != ""
  failed_when: false
  become: true
  tags: [ maintenance, cleanup, packages, debug ]
