---
# Tasks for cleaning up system files and logs

- name: Clean journal logs older than 7 days
  command: journalctl --vacuum-time=7d
  changed_when: true
  become: true
  tags: [ maintenance, cleanup, system, logs ]

- name: Clean temporary files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/*
    - /var/tmp/*
  ignore_errors: yes
  become: true
  tags: [ maintenance, cleanup, system, temp ]

- name: Clear user cache directories
  file:
    path: "{{ ansible_env.HOME }}/.cache/{{ item }}"
    state: absent
  with_items:
    - mozilla
    - chromium
    - spotify
  ignore_errors: yes
  tags: [ maintenance, cleanup, system, cache ]

- name: Remove files in .cache/ueberzugpp older than 30 days
  shell: find {{ ansible_env.HOME }}/.cache/ueberzugpp -type f -mtime +30 -delete
  changed_when: false
  ignore_errors: yes
  tags: [ maintenance, cleanup, system, cache ]

- name: Remove files in .cache/lf older than 30 days
  shell: find {{ ansible_env.HOME }}/.cache/lf -type f -mtime +30 -delete
  changed_when: false
  ignore_errors: yes
  tags: [ maintenance, cleanup, system, cache ]

- name: Remove files in .cache/qimgv/thumbnails older than 30 days
  shell: find {{ ansible_env.HOME }}/.cache/qimgv/thumbnails -type f -mtime +30 -delete
  changed_when: false
  ignore_errors: yes
  tags: [ maintenance, cleanup, system, cache ]

- name: Clean broken symlinks in user home
  shell: find {{ ansible_env.HOME }} -xtype l -delete
  become: true
  changed_when: false
  ignore_errors: yes
  tags: [ maintenance, cleanup, system, symlinks ]
