---
# Tasks for keeping the system updated

- name: Update pacman mirrors for faster downloads
  command: reflector --country 'France' --latest 20 --sort rate --save /etc/pacman.d/mirrorlist
  changed_when: true
  become: true
  ignore_errors: yes
  tags: [maintenance, update, mirrors]

- name: Update package database
  pacman:
    update_cache: yes
  become: true
  tags: [maintenance, update, packages]

- name: Upgrade all packages
  pacman:
    upgrade: yes
  become: true
  tags: [maintenance, update, packages]

- name: Update AUR packages using yay
  shell: yay -Syu --noconfirm
  become: false
  changed_when: true
  register: yay_result
  failed_when: yay_result.rc != 0 and 'error' in yay_result.stderr
  tags: [maintenance, update, aur]
