#!/bin/bash
set -euo pipefail

# =============================================================================
# CONFIGURATION
# =============================================================================

# List of files that MUST be encrypted.
# Add new sensitive files here.
FILES_TO_ENCRYPT=(
    'group_vars/all/vault.yml'
    'roles/apps/voxtype/defaults/secret.yml'
    'roles/system/files/etc/wireguard/Peer_FC_L-ANTLIA.conf'
    'roles/system/files/etc/wireguard/Peer_LP_L-CENTAURUS.conf'
)

PASSWORD_SCRIPT="./password.sh"

# =============================================================================
# FUNCTIONS
# =============================================================================

# Check if a file is ansible-vault encrypted
is_encrypted() {
    local file="$1"
    [[ -f "$file" ]] && head -n 1 "$file" | grep -q "\$ANSIBLE_VAULT;"
}

# Get the vault password argument
get_vault_arg() {
    if [ -f "$PASSWORD_SCRIPT" ] && [ -x "$PASSWORD_SCRIPT" ]; then
        echo "--vault-password-file $PASSWORD_SCRIPT"
    else
        echo ""
    fi
}

# Install the git pre-commit hook
install_hook() {
    local hook_path=".git/hooks/pre-commit"
    echo "🪝 Installing pre-commit hook to $hook_path..."
    
    cat <<EOF > "$hook_path"
#!/bin/sh
# Auto-generated by encrypt.sh
# Checks for unencrypted secrets before committing.

# Ensure we are in the repo root
REPO_ROOT=\$(git rev-parse --show-toplevel)
exec "\$REPO_ROOT/encrypt.sh" --check
EOF

    chmod +x "$hook_path"
    echo "✅ Hook installed! Unencrypted secrets will now block commits."
}

# Check files (for pre-commit hook)
check_files() {
    local failed=0
    echo "🔍 Scanning for unencrypted secrets..."
    
    for file in "${FILES_TO_ENCRYPT[@]}"; do
        if [ ! -f "$file" ]; then
            continue
        fi

        if ! is_encrypted "$file"; then
            echo "❌ SECURITY ERROR: Found unencrypted secret file!"
            echo "   File: $file"
            failed=1
        fi
    done

    if [ "$failed" -eq 1 ]; then
        echo ""
        echo "⛔ Commit blocked."
        echo "💡 Run './encrypt.sh' to encrypt these files before committing."
        exit 1
    fi
    
    echo "✅ No unencrypted secrets found."
}

# Encrypt files
encrypt_files() {
    local vault_arg
    vault_arg=$(get_vault_arg)
    
    if [ -z "$vault_arg" ]; then
        echo "ℹ️  No executable '$PASSWORD_SCRIPT' found."
        echo "   You will be prompted for the vault password for each file."
    else
        echo "🔑 Using '$PASSWORD_SCRIPT' for automation."
    fi

    for file in "${FILES_TO_ENCRYPT[@]}"; do
        if [ ! -f "$file" ]; then
            # Silently skip missing files (or warn if verbose)
            # echo "⚠️  Skipping missing file: $file"
            continue
        fi

        if is_encrypted "$file"; then
            echo "✅ Already encrypted: $file"
        else
            echo "🔒 Encrypting: $file"
            # We use eval to handle the empty vault_arg correctly if it's empty
            if [ -n "$vault_arg" ]; then
                ansible-vault encrypt "$file" $vault_arg
            else
                ansible-vault encrypt "$file"
            fi
        fi
    done
    echo "✨ All present files are encrypted."
}

# =============================================================================
# MAIN
# =============================================================================

# Parse arguments
if [ $# -gt 0 ]; then
    case "$1" in
        --install-hook)
            install_hook
            ;;
        --check)
            check_files
            ;;
        --help|-h)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  (no args)       Scans and encrypts any plaintext secret files."
            echo "  --install-hook  Installs the git pre-commit hook."
            echo "  --check         Checks for unencrypted files (used by hook)."
            echo "  --help          Show this help."
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
else
    encrypt_files
fi
