---
# Handlers for common role

- name: Restart greetd
  ansible.builtin.service:
    name: greetd
    state: restarted
  become: true

- name: Restart waybar
  ansible.builtin.command: pkill -SIGUSR2 waybar
  failed_when: false
  changed_when: true
  become: true
