#! /bin/sh

dunst &
~/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            2
bspc config window_gap              8

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config ignore_ewmh_focus       true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a *:dropdown state=floating sticky=on

brightwhite=#F5F5F5
white=#D1D1D1
brightblack=#292929
black=#0F0F0F
brightblue=#4958F5
blue=#525CCC
brightred=#F53131
red=#CC3D3D
cyan=#2D57CC

# Colors
bspc config focused_border_color            "#999999"
bspc config active_border_color             "#2D2154"
bspc config normal_border_color             "#242424"
bspc config urgent_border_color             "#B52630"
# bspc config focused_locked_border_color     "$brightred"
# bspc config active_locked_border_color      "$red"
# bspc config normal_locked_border_color      "$black"
# bspc config focused_sticky_border_color     "$brightcyan"
# bspc config active_sticky_border_color      "$cyan"
# bspc config normal_sticky_border_color      "$black"
# bspc config focused_private_border_color    "$brightblue"
# bspc config active_private_border_color     "$blue"
# bspc config normal_private_border_color     "$black"

bspc config presel_feedback_color            "#5359A3"

# Set wallpaper
chbg &
