---
- name: Ensure /usr/bin directory exists
  ansible.builtin.file:
    path: /usr/bin
    state: directory
    mode: '0755'
  become: true

- name: Copy system scripts to /usr/bin
  ansible.builtin.copy:
    src: "usr/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    mode: '0755'
    owner: root
    group: root
  loop:
    - sound
    - play-pause
    - transcript
    - xdg-open
  become: true

- name: Sync local scripts
  ansible.posix.synchronize:
    src: 'home/.local/bin/'
    dest: '{{ ansible_facts["user_dir"] }}/.local/bin/'
    recursive: true
#  become: true

- name: Set script files permissions
  ansible.builtin.file:
    path: '{{ ansible_facts["user_dir"] }}/.local/bin/'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'
    recurse: true
  become: true
