---
- name: Install necessary packages
  community.general.pacman:
    name:
      - zsh
      - curl
      - git
      - zoxide
      - fzf
      - bat
      - eza
      - fd
      - ripgrep
      - micro
      - kakoune
      - progress
    state: present
  become: true
  tags: [ system, zsh, core ]

- name: Install necessary packages with yay (Arch)
  shell: 'yay -Sy --noconfirm {{ item }}'
  become: true
  become_user: '{{ ansible_user }}'
  loop:
    - zsh-autopair-git
    - zsh-autosuggestions
    - zsh-completions
    - zsh-syntax-highlighting
  when: ansible_facts.distribution == 'Archlinux'
  tags: [ system, zsh, plugins ]

- name: Configure global ZDOTDIR in /etc/zsh/zshenv
  become: true
  template:
    src: etc/zsh/zshenv.j2
    dest: /etc/zsh/zshenv
    mode: '0644'
  tags: [ system, zsh, config ]

- name: Deploy system-wide shell configuration (dotarch.sh)
  become: true
  template:
    src: etc/profile.d/dotarch.sh.j2
    dest: /etc/profile.d/dotarch.sh
    mode: '0644'
  tags: [ system, zsh, config ]

- name: Configure global Zsh settings (zshrc)
  become: true
  template:
    src: etc/zsh/zshrc.j2
    dest: /etc/zsh/zshrc
    mode: '0644'
  tags: [ system, zsh, config ]

- name: Ensure .config/zsh directory exists
  file:
    path: '{{ ansible_facts["user_dir"] }}/.config/zsh'
    state: directory
  tags: [ system, zsh, directory ]

- name: Ensure .cache/zsh directory exists
  file:
    path: '{{ ansible_facts["user_dir"] }}/.cache/zsh'
    state: directory
  tags: [ system, zsh, directory ]

#TODO find a way to clean and merge between saved and deployed one
#-  name: Copy zsh history
#   copy:
#      src: 'home/.cache/zsh/history'
#      dest: '{{ ansible_facts["user_dir"] }}/.cache/zsh/history'

- name: Clone oh-my-zsh (Global)
  become: true
  git:
    repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
    dest: '/usr/share/oh-my-zsh'
    clone: true
    update: true
  tags: [ system, zsh, plugins, ohmyzsh ]
