---
-  name: Install necessary packages with pacman
   pacman:
      name:
         - bluez
         - bluez-obex

- name: Set Bluetooth auto-enable
  lineinfile:
     path: /etc/bluetooth/main.conf
     regexp: '^#?AutoEnable=true'
     line: 'AutoEnable=true'
     backrefs: yes
     state: present

- name: Enable bluetooth service to activate bluetooth on boot
  systemd:
     name: bluetooth.service
     enabled: yes
     state: started
  become: yes
