---
-  name: Ensure POOL_1_DATA mount is present in fstab
   lineinfile:
      dest: /etc/fstab
      line: '//10.0.0.1/pool_1_data /mnt/POOL_1_DATA cifs x-systemd.automount,_netdev,credentials=/etc/.cifscredentials,iocharset=utf8,acl,noperm 0 0'
      state: present
   become: yes

-  name: Copy .cifscredentials for fstab cifs mount
   copy:
      src: 'etc/.cifscredentials'
      dest: '/etc/.cifscredentials'
      mode: '0600'
      owner: root
      group: root
   become: yes
