---
-  name: Ensure systemd getty for tty1 directory exists
   file:
      path: '/etc/systemd/system/getty@tty1.service.d'
      state: directory
   become: yes

-  name: Copy skip-username.conf for getty config
   template:
      src: 'etc/systemd/system/getty@tty1.service.d/skip-username.conf.j2'
      dest: '/etc/systemd/system/getty@tty1.service.d/skip-username.conf'
   become: yes
