---
- include_tasks: yay.yml
- include_tasks: packages.yml
- include_tasks: zsh.yml
- include_tasks: hostname.yml
- include_tasks: bluetooth.yml
- include_tasks: pipewire.yml
- include_tasks: numlock.yml
- include_tasks: getty.yml
- include_tasks: fstab.yml
- include_tasks: scripts.yml
- include_tasks: virtualization.yml


# TODO make system.yml laptop specific

#-  name: Install packages
#   shell: >
#      pacman -Syu --noconfirm
#      acpi
#      acpilight
#      arc-icon-theme
#      broot
#      bumblebee
#      clipnotify
#      connect-tunnel
#      ctpv-git
#      dark-icon-theme-git
#      davfs2
#      i3lock-color
#      lxappearance
#      materia-gtk-theme
#      mediainfo
#      mesa-utils
#      papirus-icon-theme
#      qt-avif-image-plugin-libavif-git
#      qt5-styleplugins
#      rshred-git
#      touchegg
#   become: yes
