---

# Audio tools
-  name: Install audio tools
   pacman:
      name:
         - pandoc-cli
         - alsa-utils
         - pulsemixer
         - playerctl
      state: present
   become: yes

# System tools
-  name: Install system tools
   pacman:
      name:
         - docker
         - docker-compose
         - man-db
         - btop
         - nvtop
         - progress
         - usbutils
         - socat
         - handlr-regex
         - rsync
         - wget
      state: present
   become: yes

# Xorg tools
-  name: Install Xorg tools
   pacman:
      name:
         - arandr
         - xorg-server-xephyr
         - xorg-xdpyinfo
         - xorg-xev
         - xorg-xinit
         - xorg-xinput
         - wmctrl
      state: present
   become: yes

# Network tools
-  name: Install network tools
   pacman:
      name:
         - ldns # Provide drill command
         - cifs-utils
      state: present
   become: yes

# Math tools
-  name: Install math tools
   pacman:
      name:
         - bc
         - qalculate-gtk
      state: present
   become: yes

# TeXlive tools
-  name: Install TeXlive tools
   pacman:
      name:
         - texlive-bibtexextra
         - texlive-fontsextra
         - texlive-langfrench
         - texlive-latexextra
      state: present
   become: yes

-  name: Install necessary packages
   shell: >
      yay -Sy --noconfirm 
      dasel-bin
      task-spooler
      texlive-latexindent-meta
   become: yes
   become_user: '{{ username }}'
