
services:
   ansible:
      build:
         context: .
      networks:
         default:
            aliases:
               - host.docker.internal
      environment:
         ENCRYPT: "true"
         DEPLOY: "true"
      volumes:
         - .:/ansible
         - ~/.ssh:/root/.ssh
