---
-  name: Copy the bitwarden password file
   copy:
      src: 'home/.config/Bitwarden CLI/.pass'
      dest: '/home/{{ username }}/.config/Bitwarden CLI/.pass'
      mode: '0600'
      owner: '{{ username }}'
      group: '{{ username }}'

-  name: Configure the bitwarden server
   shell: |
      state=$(bw status | jq -r '.status')
      if [ "$state" == "unauthenticated" ];
         then bw config server vault.phosmachina.com;
      elif [ "$state" != "unlocked" ]; then
         echo "Bitwarden is in an invalid state: $state"
         exit 1
      fi
   changed_when: false
   failed_when: false
