---
-  name: Copy xinit configuration
   copy:
      src: 'home/.xinitrc'
      dest: '/home/{{ username }}/.xinitrc'

-  name: Copy .zprofile configuration
   copy:
      src: 'home/.zprofile'
      dest: '/home/{{ username }}/.zprofile'

-  name: Ensure rofi theme directory exists
   file:
      path: '/usr/share/rofi/themes'
      state: directory

-  name: Copy the rofi theme
   copy:
      src: 'usr/share/rofi/themes/spotlight-custom.rasi'
      dest: '/usr/share/rofi/themes/spotlight-custom.rasi'
   become: yes

-  name: Sync herbstluftwm and all others wm relative configs
   synchronize:
      src: 'home/.config/{{ item }}'
      dest: '/home/{{ username }}/.config/'
   with_items:
      - herbstluftwm
      - picom
      - rofi
      - dunst
      - kitty
      - polybar
      - micro
   become: yes
   become_user: '{{ username }}'

-  name: Ensure handlr directory exists
   file:
      path: '/home/{{ username }}/.config/handlr'
      state: directory

-  name: Copy handlr config
   copy:
      src: 'home/.config/handlr/handlr.toml'
      dest: '/home/{{ username }}/.config/handlr/handlr.toml'

-  name: Clone themes for kitty
   git:
      repo: 'https://github.com/dexpota/kitty-themes'
      dest: '/home/{{ username }}/.config/kitty/kitty-themes'
      clone: yes
      update: yes
