---
-  name: Ensure keymap directory exists
   file:
      path: '/home/{{ username }}/.config/keymap'
      state: directory

-  name: Copy us_custom keymap to config
   copy:
      src: 'home/.config/keymap/us_custom'
      dest: '/home/{{ username }}/.config/keymap/us_custom'

-  name: Backup remote US keymap
   copy:
      src: '/usr/share/X11/xkb/symbols/us'
      dest: '/home/{{ username }}/.config/keymap/us_backup'
      remote_src: yes
   become: yes

-  name: Override us with us_custom keymap
   copy:
      src: '/home/{{ username }}/.config/keymap/us_custom'
      dest: '/usr/share/X11/xkb/symbols/us'
      remote_src: yes
   become: yes
