---
-  name: Install some desktop applications
   pacman:
      name:
         - firefox
         - xfce4-power-manager
         - syncthing
         - telegram-desktop
         - discord
      state: present
   become: yes

-  name: Install some desktop apps from AUR
   shell: 'yay -Sy --noconfirm {{ aur_packages }}'
   become: yes
   become_user: '{{ username }}'
   vars:
      aur_packages:
         - jetbrains-toolbox
         - tidal-hifi-bin
         - surfshark-client
         - visual-studio-code-bin
#         - spotify-adblock-git
