---
-  name: Install some desktop applications
   pacman:
      name:
         - firefox
         - xfce4-power-manager
         - syncthing
         - telegram-desktop
         - discord
      state: present
   become: yes

-  name: Install some desktop apps from AUR
   shell: >
      yay -Sy --noconfirm 
      jetbrains-toolbox
      spotify-adblock-git
      surfshark-client
      visual-studio-code-bin
   become: yes
   become_user: '{{ username }}'
