---
-  name: Install necessary packages with pacman
   pacman:
      name:
         - curl
         - git
         - zsh
         - zoxide
         - fzf
         - bat
         - eza
         - micro
         - kakoune
         - progress
      state: present
   become: yes

-  name: Install necessary packages with yay
   shell: >
      yay -Sy --noconfirm 
      zsh-autopair-git
      zsh-autosuggestions 
      zsh-completions 
      zsh-syntax-highlighting
   become: yes
   become_user: '{{ username }}'

-  name: Copy aliasrc
   copy:
      src: 'home/.config/zsh/aliasrc'
      dest: '/home/{{ username }}/.config/zsh/aliasrc'
      mode: '0644'
      owner: '{{ username }}'
      group: '{{ username }}'

-  name: Copy functionrc
   copy:
      src: 'home/.config/zsh/functionrc'
      dest: '/home/{{ username }}/.config/zsh/functionrc'
      mode: '0644'
      owner: '{{ username }}'
      group: '{{ username }}'

- name: Ensure .config/zsh directory exists
  file:
     path: '/home/{{ username }}/.config/zsh'
     state: directory

-  name: Copy zsh config
   copy:
      src: 'home/.config/zsh/.zshrc'
      dest: '/home/{{ username }}/.config/zsh/.zshrc'

- name: Ensure .cache/zsh directory exists
  file:
     path: '/home/{{ username }}/.cache/zsh'
     state: directory

#-  name: Copy zsh history
#   copy:
#      src: 'home/.cache/zsh/history'
#      dest: '/home/{{ username }}/.cache/zsh/history'

-  name: Clone oh-my-zsh
   git:
      repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
      dest: '/home/{{ username }}/.config/zsh/ohmyzsh'
      clone: yes
      update: yes

#Require interaction; how to skip it?
#-  name: Install Oh-my-zsh
#   shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
#   args:
#      chdir: "/home/{{ username }}/.config/zsh"
#   become: yes
#   become_user: "{{ username }}"

-  name: Set zsh as default shell
   shell: chsh -s $(which zsh) "{{ username }}"
   become: yes
